import ProjectDetail from '@/components/ProjectDetail';

const projectData: Record<string, any> = {
  'akash-inn-hotel': {
    title: 'Akash Inn Hotel',
    category: 'Hospitality',
    location: 'India',
    cover: '/h9y/Akash%20Inn%20Hotel/akash%201.jpg',
    year: '2014',
    scope: 'Interior Design & FF&E',
    budget: '—',
    timeline: '—',
    description: 'A hospitality project featuring warm palettes and functional layouts tailored for guest comfort and operational efficiency.',
    challenge: 'Deliver elevated experience within existing building constraints and schedule.',
    solution: 'Optimized circulation, layered lighting, and durable finishes for high-traffic areas.',
    images: [
      '/h9y/Akash%20Inn%20Hotel/akash%201.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%202.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%203.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%204.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%205.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%206.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%207.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%208.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%209.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2010.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2011.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2012.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2013.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2014.jpg',
      '/h9y/Akash%20Inn%20Hotel/akash%2015.jpg',
    ],
  },
  'halcyon-hotel-residential': {
    title: 'Halcyon Hotel (Residential)',
    category: 'Residential',
    location: 'India',
    year: '—',
    scope: 'Interior Design',
    budget: '—',
    timeline: '—',
    description: 'Calm residential environments with soft textures, warm light, and thoughtful details.',
    challenge: 'Balance comfort and simplicity without compromising spatial function.',
    solution: 'Neutral materials with accent textures and efficient storage planning.',
    images: [
       '/h9y/Halcyon%20Hotel%20Residenstiol/gl_22.jpg',
      '/h9y/Halcyon%20Hotel%20Residenstiol/gl_14.jpg',
      '/h9y/Halcyon%20Hotel%20Residenstiol/gl_19.jpg',
      '/h9y/Halcyon%20Hotel%20Residenstiol/gl_6.jpg',
    ],
  },
  'la-sara-hotel': {
    title: 'La Sara Hotel',
    category: 'Hospitality',
    location: 'Bengaluru, India',
    cover: '/h9y/La%20Sara%20Hotel/breakfast%20area.jpg',
    year: '—',
    scope: 'Accommodation Interiors',
    budget: '—',
    timeline: '—',
    description: 'Guest rooms with a contemporary aesthetic and a focus on comfort and durability.',
    challenge: 'Create a cohesive guest experience across multiple room types.',
    solution: 'Unified palette and modular detailing for efficient execution.',
    images: [
      '/h9y/La%20Sara%20Hotel/breakfast%20area.jpg',
      
      '/h9y/La%20Sara%20Hotel/Kormangla-Ac4.jpg',
      '/h9y/La%20Sara%20Hotel/Kormangla-Ac5.jpg',
      '/h9y/La%20Sara%20Hotel/La-Sara-Grand-Accomodation.webp',
      '/h9y/La%20Sara%20Hotel/1.jpg',
      '/h9y/La%20Sara%20Hotel/bf%20area%202.jpg',
      '/h9y/La%20Sara%20Hotel/dinning1.webp',
      '/h9y/La%20Sara%20Hotel/lift-area.jpg',
      '/h9y/La%20Sara%20Hotel/Kormangla-Ac3.jpg',
    ],
  },
  'nandhana-palace-restaurant': {
    title: 'Nandhana Palace Restaurant',
    category: 'Hospitality',
    location: 'India',
    year: '—',
    scope: 'Restaurant Interiors',
    budget: '—',
    timeline: '—',
    description: 'Dining spaces designed for throughput, acoustics, and comfortable ambience.',
    challenge: 'Manage acoustics and durability in a high-traffic restaurant.',
    solution: 'Acoustic treatments and robust materials with warm finishes.',
    images: [
      '/h9y/Nandhana%20Palace%20Restorant/1.webp',
      '/h9y/Nandhana%20Palace%20Restorant/2.JPG',
      '/h9y/Nandhana%20Palace%20Restorant/3.JPG',
      '/h9y/Nandhana%20Palace%20Restorant/4.JPG',
      '/h9y/Nandhana%20Palace%20Restorant/5.webp',
      '/h9y/Nandhana%20Palace%20Restorant/6.webp',
      '/h9y/Nandhana%20Palace%20Restorant/7.webp',
      '/h9y/Nandhana%20Palace%20Restorant/8.webp',
    ],
  },
  'windflower-varca-goa': {
    title: 'The Windflower Resort & Spa, Varca (Goa)',
    category: 'Hospitality',
    location: 'Goa, India',
    cover: '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home.jpg',
    year: '—',
    scope: 'Resort Interiors & FF&E',
    budget: '—',
    timeline: '—',
    description: 'Resort environment blending relaxed coastal tones with durable, guest-friendly finishes.',
    challenge: 'Express a premium resort feel while ensuring longevity in a coastal climate.',
    solution: 'Corrosion-conscious hardware, easy-care fabrics, and layered lighting.',
    images: [
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home2.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home3.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home4.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home5.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home6.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home7.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home8.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home9.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home10.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home11.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home12.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home13.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home14.jpg',
      '/h9y/THE%20WINDFLOWER%20Resort%20%26%20Spa%20Varca%20Goa/home15.jpg',
    ],
  },
  iconiqa: {
    title: 'ICONIQA Hotel Mumbai International Airport',
    category: 'Turnkey',
    location: 'India',
    cover: '/h9y/iconiqa/iconiqa 1.png',
    year: '—',
    scope: 'Retail / Interior environments',
    budget: '—',
    timeline: '—',
    description: "The hotel features 291 rooms across seven categories, starting from 250 sq. ft. up to 850 sq. ft. suites, each equipped with carefully planned amenities tailored for modern travellers. It is positioned as the world’s first hotel where all rooms include an in-room smart laundry closet, removing the inconvenience of quick ironing or freshening clothing. Each room also includes an espresso machine with custom coffee pods and thoughtful interior touches. The overall design combines Art Deco influences, Parisian flair, and hyperlocal details, with custom lighting and a unique pixelated reinterpretation of a Kashmiri rug at the reception.",
    challenge: "Travellers often face inconvenience with last-minute garment preparation, such as ironing jackets, shirts, or traditional wear like salwar kameez. Hotels commonly struggle to provide a seamless, quick, and tech-enabled guest service experience without delays or dependency on manual processes. Balancing modern luxury with authentic local design elements while maintaining a consistent aesthetic throughout the property.",
    solution: "Introducing an in-room smart laundry closet solves the garment-care problem by eliminating the need for manual ironing or steaming. A fully digital, guest-centric service layer (WhatsApp-powered support, quick ordering of services, linen, food, etc.) ensures instant hospitality with no app downloads or waiting. Thoughtful design elements—custom chandeliers, Art Deco-Parisian blend, pixelated Kashmiri rug artwork—create a unique, immersive luxury experience aligned with modern traveller expectations.",
    images: [
      '/h9y/iconiqa/iconiqa 1.png',
      '/h9y/iconiqa/iconiqa 2.jpg',
      '/h9y/iconiqa/iconiqa 3.jpg',
      '/h9y/iconiqa/iconiqa 4.jpg',
      '/h9y/iconiqa/iconiqa 5.webp',
      '/h9y/iconiqa/iconiqa 6.jpg',
      '/h9y/iconiqa/iconiqa 7.jpg',
      '/h9y/iconiqa/iconiqa 8.jpg',
      '/h9y/iconiqa/iconiqa 9.jpg',
      '/h9y/iconiqa/iconiqa 10.jpg',
      '/h9y/iconiqa/iconiqa 11.jpg',
      '/h9y/iconiqa/iconiqa 12.jpg',
      '/h9y/iconiqa/iconiqa 13.jpg',
      '/h9y/iconiqa/iconiqa 14.jpg',
      '/h9y/iconiqa/iconiqa 15.jpg',
      '/h9y/iconiqa/iconiqa 16.webp',
      '/h9y/iconiqa/iconiqa 17.jpg',
      '/h9y/iconiqa/iconiqa 18.jpg',
      '/h9y/iconiqa/iconiqa 19.webp',
      '/h9y/iconiqa/iconiqa 20.webp',
      '/h9y/iconiqa/iconiqa 21.webp',
      '/h9y/iconiqa/iconiqa 22.jpg',
      '/h9y/iconiqa/iconiqa 23.jpg',
      '/h9y/iconiqa/iconiqa 24.webp',
      '/h9y/iconiqa/iconiqa 25.jpg',
      '/h9y/iconiqa/iconiqa 26.jpg',
      '/h9y/iconiqa/iconiqa 27.jpg',
      '/h9y/iconiqa/iconiqa 28.webp',
      '/h9y/iconiqa/iconiqa 29.jpg',
      '/h9y/iconiqa/iconiqa 30.webp',
      '/h9y/iconiqa/iconiqa 31.jpg',
      '/h9y/iconiqa/iconiqa 32.webp',
      '/h9y/iconiqa/iconiqa 33.jpg',
    ],
  },
};

export async function generateStaticParams() {
  return Object.keys(projectData).map((slug) => ({ slug }));
}

export default function ProjectDetailPage({ params }: { params: { slug: string } }) {
  const project = projectData[params.slug] || projectData['akash-inn-hotel'];

  return <ProjectDetail project={project} />;
}
